import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "File Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between border-b-2 p-6">
          <Link href={"/"} className="text-3xl">
            File Management System
          </Link>

          <Link href="/upload" className=" rounded bg-black p-3 text-white">
            Upload Image
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
